### ISSUE TITLE
cash.js sendCashFrom() allows for sending of -eth

### ISSUE THREAD

**Issue by JohnDanz** [AugurProject/augur.js#142]
I'm using the sendCashFrom() function to facilitate sending eth from one user to another. The issue is that you can send -eth and it works and takes eth from the person the "to" person. I could set the send Eth input box to not allow negative numbers but that seems like a bandaid fix and this function should probably do some checks that:

the amount isn't negative.
The from user has enough cash/eth to send the requested amount.

**Comment by joeykrug** [comment]
Not possible: https://github.com/AugurProject/augur-core/blob/master/src/data_api/cash.se#L78

**Comment by tinybike** [comment]
@JohnDanz can you provide an example of this?  Preferred example would be manually calling `augur.sendCashFrom` from your Browser/Node console, so that you're 100% sure what the parameters are, and then pasting:
- the exact parameters you passed to `augur.sendCashFrom`
- the response you get from `augur.sendCashFrom`
- before and after `augur.getCashBalance` responses for the sending and receiving accounts

**Comment by JohnDanz** [comment]
Nevermind, Joey is correct.
