### ISSUE TITLE
Batch RPC interface

### ISSUE THREAD

**Issue by niran** [AugurProject/augur.js#17]
Here are the three options I think we have:

Option 1
```
Augur.batch(function (augur) {
    augur.methodName(..., callback1);
    augur.methodName(..., callback2);
});
```

Option 2
```
var batch = Augur.batch();
batch.methodName(..., callback1);
batch.methodName(..., callback2);
batch.execute();
```

Option 3
```
var batch = Augur.batch();
Augur.methodName(..., callback1, batch);
Augur.methodName(..., callback2, batch);
batch.execute();
```

I think Option 1 is the nicest to use, but potentially awkward to implement. Option 2 seems like the middle ground on usability and implementation difficulty. Option 3 is probably pretty terrible since Javascript doesn't give us default argument values to make it easier to distinguish between all of the optional callbacks and the batch.

**Comment by tinybike** [comment]
I think you're right that option 3 isn't practical.  I should be able to implement either option 1 or 2 without too much difficulty (famous last words, ha).  I'll try option 1 since that's your preference.

I should add that there already is a batch RPC method, albeit not a terribly user-friendly one.  The way it works at the moment is you hand it an array of transactions you want executed, and it sends them, then returns an array with your results.  The transactions are all bundled into the `Augur.tx` object, so for example:
```
Augur.tx.getCashBalance.params = Augur.coinbase;
Augur.tx.getRepBalance.params = [Augur.branches.dev, Augur.coinbase];
var txlist = [Augur.tx.getCashBalance, Augur.tx.getRepBalance];
var results = Augur.batch(txlist); // synchronous
Augur.batch(txlist, function (results) { ... }); // asynchronous
```
But, I'll wrap this with a method that lets you use a nicer syntax -- understandable to not want to deal with the `Augur.tx` object manually!

**Comment by tinybike** [comment]
Added a modified version of option 2 in 32ed88e.
