### ISSUE TITLE
please hand contract addresses object off of Augur.constants

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#39]
such as:
`Augur.constants.CONTRACT_ADDRESSES[7]`
the index value being a network id.  in this case '7'.

the result would be an object containing all the contracts by our naming convention and the current address.  exactly how you have it.

**Comment by tinybike** [comment]
I suggest using the [augur-contracts](https://github.com/AugurProject/augur-contracts) module directly (rather than augur.js, which just uses the active set of contracts):
```javascript
var contracts = require('augur-contracts');
```
The `contracts` object is organized the way you're requesting: for example, use `contracts[7].events` to grab the events contract address on network 7.
