### ISSUE TITLE
unable to sign into previously registered account

### ISSUE THREAD

**Issue by scottzer0** [AugurProject/augur.js#43]
i never seem to be able to sign into an account i "registered".  i get `sign in failed`

**Comment by tinybike** [comment]
I haven't been able to find anything that would cause this in augur.js.  I've run the full set of [accounts unit tests](https://github.com/AugurProject/augur.js/blob/master/test/client/accounts.js) multiple times, which includes various permutations of registering / logging in / logging out  on networks 7 and 10101.  The tests always pass.  I've also tried registering / logging in manually, logging in using a previously registered account, shutting down geth then logging in using a previously registered account, etc., using the Node console and as far as I can tell there are no problems.

Given these test results, it seems very likely that this bug originates in the client rather than augur.js, so I'm closing this issue for now.  If you can provide a failing test case, please feel free to re-open this issue and I will investigate further.
