### ISSUE TITLE
Implement tags

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#55]
Latest proposal:

- save an array (order is important) of up to 3 tags on chain per market during creation
- retrieve tags in getMarketsInfo && getMarketInfo

The ui will gather and aggregate tags as markets load in, displaying the most popular tags first. @tinybike

**Comment by tinybike** [comment]
I think aggregating tags as markets load will not be good UX, as the top tags will change rapidly as the user is looking at and attempting to comprehend the landing page.  (Siimilar to how loading markets by volume is bad UX now, due to the constantly changing order of markets as they load.)  My suggestion is to store tag counts on-contract, so "most popular tags" can be looked up all at once (and separately from the initial market loading step, if desired).

**Comment by thinkloop** [comment]
You have valid points, but then it makes the implementation much more rigid and complex. Say the first set of tags are:

POLITICS
SPORTS
FINANCE

And someone selects POLITICS. The intention now is for the ui to list the next most popular tags on the remaining markets, yielding:

US PRESENDENTIAL ELECTION
RUSSIA
MIDDLE EAST
...

If someone clicks another one, we follow the same process showing the top tags of the remaining markets.

This lets us represent complex relationships between tags, without enforcing arbitrary rules.

Implementing this logic in the backend will make it much more complex, and more rigid by requiring a backend update whenever the frontend strategy is tweaked. If we keep the backend generic, we can test out various frontend strategies until we figure out whats best, then perhaps throw it into the backend.

**Comment by tinybike** [comment]
I see your point.  I guess it's kind of a tangential thing anyway, since however the back-end and the UI end up splitting this task, getMarket(s)Info will certainly fetch the tags.

**Comment by tinybike** [comment]
Added to augur-core in AugurProject/augur-core@372405a48b5ea928cabb9418d3c994b10697042b.

**Comment by tinybike** [comment]
Added in 57546a4c55eab715d57098cb61b47aa21038b651.
