### ISSUE TITLE
The Sundering

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#56]
Similar to how there is an `accounts` file, there could also be `reports`, `trade`, `markets`, etc. that get gathered into one final file at the end. This will make it easier to work with and update piece-by-piece as we go along. @tinybike

**Comment by tinybike** [comment]
I've already done this where there was any kind of natural separation.  However, it's not at all clear to me that there is anything to be gained from breaking augur.js apart further.  The methods remaining in the giant index.js file are quite hard to decouple, due to the shared use of the `augur` and `rpc` objects.

If filters were moved to ethrpc, `augur` could (with enough contortions -- accounts relies heavily on its own internal state) be made stateless, but `rpc` needs to have state.  If things are intertwined due to shared `rpc` state I don't think splitting into multiple files solves anything -- if anything, it adds a slight extra complexity from having to mentally "load up" state shared across files.

**Comment by thinkloop** [comment]
We can require instances of objects rather than their classes to maintain state between files. This is more about having the code be easier to handle from a coder perspective, rather than a big architectural change. At the same time, usually the presence of state is an added pressure to break things apart - are there not logical bundles of state that could be grouped into logical classes, I really don't know, genuinely asking.

**Comment by thinkloop** [comment]
If not, the state can be encapsulated in its own component, and passed around the other modules as needed.

**Comment by tinybike** [comment]
Another issue with this is that it would involve changing the `augur.functionName()` syntax.  Each file would (presumably) export its own functions, so the invocations would look something like `augur.markets.functionName()` instead.  I agree that this could be nice from a code organization standpoint, but I don't think that's worth breaking backwards compatibility over.

**Comment by tinybike** [comment]
`src/index.js` has gotten so large that it is now above babel's 100k size limit.  Let the shattering commence!

**Comment by tinybike** [comment]
Lots of tiny files in 6f20c1c93220e81b04e2cabd0b37e80ba5e9b091.
