### ISSUE TITLE
Change default markets sort order to highest volume?

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur.js#57]
Highest volume seems like an easy way to show best markets. There was talk of easy gaming, not sure what the outcome of that was. Perhaps we could try it out for beta anyway and see if we can figure out something around the gaming issue for launch. @tinybike

**Comment by tinybike** [comment]
This is very awkward if it's handled by the front-end, because the order is constantly changing as markets stream in.  For this to be an acceptable UX I think it would need to be on-contract.

**Comment by thinkloop** [comment]
Yes, should we go for it?

**Comment by tinybike** [comment]
The problem with this is that you can't sort the markets during the contract method call, since this could take an unbounded amount of time as the total number of markets gets very large.  To do this in a scalable way, I think you'd need to store a list of markets (separate from the main Markets data structure on markets.se) which is sorted by volume, and updated every time a trade takes place.  This would effectively be a small tax on every market created as well as every trade.  My feeling is that this is probably not worth it.  @joeykrug, can you think of a cheaper way of doing this?

**Comment by tinybike** [comment]
Closing this for now; feel free to re-open if you think this is important enough to impose costs on market creators/traders.

**Comment by joeykrug** [comment]
Doing it the sorting way is actually almost impossible re gas cost afaik. I have some other ideas tho

**Comment by thinkloop** [comment]
To know for other things, maintaining an index in the form of an array of id strings is a relatively expensive and non-feasible process?

**Comment by joeykrug** [comment]
That's super easy and cheap, but it's not what was proposed above/doesn't solve the problem.

The way to sort markets is to:
A) maintain a market cache on the community nodes
B) keep all the markets on there that aren't expired yet
C) keep it sorted, new markets added as they come in by pinging the network periodically to check
D) end user gets a pre sorted list of all markets from one of those nodes
E) any addl markets created after the latest update to the cache is done are added into the sorted list very easily client side

A) depends on another issue in augur UI repo, and I'd also say this issue should be in the augur UI repo as well
